"""empty message

Revision ID: 02_add_venue_fields_exc_genres
Revises: 01_new_migration
Create Date: 2020-12-23 11:43:44.184493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

conn = op.get_bind()
inspector = Inspector.from_engine(conn)
venue_columns = [col['name'] for col in inspector.get_columns('venues')]

# revision identifiers, used by Alembic.
revision = '02_add_venue_fields_exc_genres'
down_revision = '01_new_migration'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if 'seeking_description' not in venue_columns:
        op.add_column('venues', sa.Column('seeking_description', sa.String(length=120), nullable=True))

    if 'seeking_talent' not in venue_columns:
        op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))

    if 'website' not in venue_columns:
        op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'seeking_description')
    # ### end Alembic commands ###
