"""empty message

Revision ID: 03_add_genre_table
Revises: 02_add_venue_fields_exc_genres
Create Date: 2020-12-24 12:37:52.424887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03_add_genre_table'
down_revision = '02_add_venue_fields_exc_genres'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    genre = op.create_table('Genre',
                            sa.Column('id', sa.Integer, nullable=False, primary_key=True),
                            sa.Column('name', sa.String, nullable=False),
                            sa.PrimaryKeyConstraint('id'),
                            sa.UniqueConstraint('name')
                            )

    genres = [
        {'name': 'Alternative'},
        {'name': 'Blues'},
        {'name': 'Classical'},
        {'name': 'Country'},
        {'name': 'Electronic'},
        {'name': 'Folk'},
        {'name': 'Funk'},
        {'name': 'Hip-Hop'},
        {'name': 'Heavy Metal'},
        {'name': 'Instrumental'},
        {'name': 'Jazz'},
        {'name': 'Musical Theatre'},
        {'name': 'Pop'},
        {'name': 'Punk'},
        {'name': 'R&B'},
        {'name': 'Reggae'},
        {'name': 'Rock n Roll'},
        {'name': 'Soul'},
        {'name': 'Swing'},
        {'name': 'Other'}
    ]

    op.bulk_insert(genre, genres)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genre')
    # ### end Alembic commands ###
