"""empty message

Revision ID: 05_add_state_table
Revises: 04_add_venue_genre_relationship
Create Date: 2020-12-24 12:51:19.352876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '05_add_state_table'
down_revision = '04_add_venue_genre_relationship'
branch_labels = None
depends_on = None

conn = op.get_bind()
inspector = Inspector.from_engine(conn)
tables = inspector.get_table_names()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if 'states' not in tables:
        state = op.create_table('states',
                                sa.Column('id', sa.Integer, nullable=False, primary_key=True),
                                sa.Column('state_code', sa.String(2), nullable=False),
                                sa.PrimaryKeyConstraint('id'),
                                sa.UniqueConstraint('state_code')
                                )

    res = conn.execute("select * from states")
    results = res.fetchall()

    if len(results) == 0:
        conn.execute('ALTER SEQUENCE "states_id_seq" RESTART WITH 1;')
        conn.execute("INSERT INTO states(state_code) "
                     "VALUES ('AL'), ('AK'), ('AR'), ('AZ'), ('CA'), ('CO'),"
                     "('CT'), ('DE'), ('DC'), ('FL'), ('GA'), ('HI'), ('ID'),"
                     "('IL'), ('IN'), ('IA'), ('KS'), ('KY'), ('LA'), ('ME'), ('MT'),"
                     "('NE'), ('NV'), ('NH'), ('NJ'), ('NM'), ('NY'), ('NC'), ('ND'),"
                     "('OH'), ('OK'), ('OR'), ('MD'), ('MA'), ('MI'), ('MN'),"
                     "('MS'), ('MO'), ('PA'), ('RI'), ('SC'), ('SD'), ('TN'), ('TX'),"
                     "('UT'), ('VT'), ('VA'), ('WA'), ('WV'), ('WI'), ('WY');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if 'phones' in tables:
        op.drop_table('phones')
    op.drop_table('states')
    # ### end Alembic commands ###
