"""empty message

Revision ID: 05_add_state_table
Revises: 04_add_venue_genre_relationship
Create Date: 2020-12-24 12:51:19.352876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05_add_state_table'
down_revision = '04_add_venue_genre_relationship'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    state = op.create_table('State',
                            sa.Column('id', sa.Integer, nullable=False, primary_key=True),
                            sa.Column('state_code', sa.String(2), nullable=False),
                            sa.PrimaryKeyConstraint('id'),
                            sa.UniqueConstraint('state_code')
                            )

    states = [
        {'state_code': 'AL'},
        {'state_code': 'AK'},
        {'state_code': 'AR'},
        {'state_code': 'AZ'},
        {'state_code': 'CA'},
        {'state_code': 'CO'},
        {'state_code': 'CT'},
        {'state_code': 'DE'},
        {'state_code': 'DC'},
        {'state_code': 'FL'},
        {'state_code': 'GA'},
        {'state_code': 'HI'},
        {'state_code': 'ID'},
        {'state_code': 'IL'},
        {'state_code': 'IN'},
        {'state_code': 'IA'},
        {'state_code': 'KS'},
        {'state_code': 'KY'},
        {'state_code': 'LA'},
        {'state_code': 'ME'},
        {'state_code': 'MT'},
        {'state_code': 'NE'},
        {'state_code': 'NV'},
        {'state_code': 'NH'},
        {'state_code': 'NJ'},
        {'state_code': 'NM'},
        {'state_code': 'NY'},
        {'state_code': 'NC'},
        {'state_code': 'ND'},
        {'state_code': 'OH'},
        {'state_code': 'OK'},
        {'state_code': 'OR'},
        {'state_code': 'MD'},
        {'state_code': 'MA'},
        {'state_code': 'MI'},
        {'state_code': 'MN'},
        {'state_code': 'MS'},
        {'state_code': 'MO'},
        {'state_code': 'PA'},
        {'state_code': 'RI'},
        {'state_code': 'SC'},
        {'state_code': 'SD'},
        {'state_code': 'TN'},
        {'state_code': 'TX'},
        {'state_code': 'UT'},
        {'state_code': 'VT'},
        {'state_code': 'VA'},
        {'state_code': 'WA'},
        {'state_code': 'WV'},
        {'state_code': 'WI'},
        {'state_code': 'WY'},
    ]

    op.bulk_insert(state, states)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('State')
    # ### end Alembic commands ###
