"""empty message

Revision ID: 07_add_artist_fields_exc_genres
Revises: 06_add_phone_table
Create Date: 2021-01-14 17:02:23.115865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

conn = op.get_bind()
inspector = Inspector.from_engine(conn)
artist_columns = [col['name'] for col in inspector.get_columns('artists')]


# revision identifiers, used by Alembic.
revision = '07_add_artist_fields_exc_genres'
down_revision = '06_add_phone_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if 'seeking_description' not in artist_columns:
        op.add_column('artists', sa.Column('seeking_description', sa.String(length=120), nullable=True))

    if 'seeking_venue' not in artist_columns:
        op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))

    if 'website' not in artist_columns:
        op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website')
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
