"""empty message

Revision ID: 08_add_artist_genre_relationship
Revises: 07_add_artist_fields_exc_genres
Create Date: 2021-01-14 17:05:23.115865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '08_add_artist_genre_relationship'
down_revision = '07_add_artist_fields_exc_genres'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'artist_genres' not in tables:
        op.create_table('artist_genres',
        sa.Column('genre_id', sa.Integer(), nullable=False),
        sa.Column('artist_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
        sa.PrimaryKeyConstraint('genre_id', 'artist_id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_genres')
    # ### end Alembic commands ###