"""empty message

Revision ID: 09_add_show_model
Revises: 08_add_artist_genre_relationship
Create Date: 2021-01-18 04:48:41.140476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '09_add_show_model'
down_revision = '08_add_artist_genre_relationship'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'shows' not in tables:
        op.create_table('shows',
                        sa.Column('artist_id', sa.Integer(), nullable=False),
                        sa.Column('show_datetime', sa.DateTime(), nullable=True),
                        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
                        sa.ForeignKeyConstraint(['venue_id'], ['venues.id']),
                        sa.PrimaryKeyConstraint('id')
                        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
