"""empty message

Revision ID: 09_add_show_model
Revises: 08_add_artist_genre_relationship
Create Date: 2021-01-18 04:48:41.140476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '09_add_show_model'
down_revision = '08_add_artist_genre_relationship'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'Show' not in tables:
        op.create_table('Show',
                        sa.Column('artist_id', sa.Integer(), nullable=False),
                        sa.Column('date', sa.Date(), nullable=True),
                        sa.Column('time', sa.Time(), nullable=True),
                        sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
                        sa.ForeignKeyConstraint(['venue_id'], ['Venue.id']),
                        sa.PrimaryKeyConstraint('id')
                        )
    # ### end Alembic commands ###


meta = sa.MetaData(bind=op.get_bind())
my_table = sa.Table('Show', meta)

my_table_constraints = list(my_table.constraints)
my_constraint_names = list(map(lambda x: x.name, my_table_constraints))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
